spring:
  application:
    name: company-directory
  datasource:
    url: jdbc:h2:file:./companydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    #show-sql: true
    #open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080
